trigger:

branches:
  include:
    - develop

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: tpfinal-vars

jobs:
  - job: BuildFront
    displayName: "Build Vue.js et publication artefact"
    steps:
      - template: templates/_build-front.yml
