steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
      displayName: "Installer Node.js 20"

  - script: npm ci
    displayName: "Install pnpm"

  - script: npm run build
    displayName: "Compiler"
    env:
      VITE_BUILD_ID: $(Build.SourceVersion)

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "dist"
      ArtifactName: "front-dist"
      displayName: "Public"
